.open company.db

CREATE TABLE Employees (
    ID INT PRIMARY KEY,
    Name NVARCHAR(50),
    Position NVARCHAR(50)
);


INSERT INTO Employees (ID, Name, Position) VALUES
(1, 'John Doe', 'Developer'),
(2, 'Jane Smith', 'Manager'),
(3, 'Bob Johnson', 'Designer'),
(4, 'Alice Brown', 'Engineer'),
(5, 'Charlie Davis', 'Analyst'),
(6, 'David White', 'Coordinator'),
(7, 'Eva Black', 'Supervisor'),
(8, 'Frank Miller', 'Programmer'),
(9, 'Grace Wilson', 'Architect'),
(10, 'Harry Turner', 'Tester'),
(11, 'Ivy Roberts', 'Administrator'),
(12, 'Jack Anderson', 'Consultant'),
(13, 'Kelly Thompson', 'Team Lead'),
(14, 'Leo Hernandez', 'Data Scientist'),
(15, 'Mia Taylor', 'Project Manager'),
(16, 'Nick Garcia', 'Support Specialist'),
(17, 'Olivia Hall', 'UX Designer'),
(18, 'Peter Moore', 'Quality Assurance'),
(19, 'Quinn Lewis', 'Technical Writer'),
(20, 'Rachel Adams', 'Systems Analyst'),
(21, 'Samuel Wright', 'Database Administrator'),
(22, 'Tina Martinez', 'Business Analyst'),
(23, 'Ulysses Clark', 'Network Engineer'),
(24, 'Violet Baker', 'Security Officer'),
(25, 'William Lee', 'DevOps Engineer'),
(26, 'Xavier King', 'Product Owner'),
(27, 'Yara Garcia', 'Scrum Master'),
(28, 'Zane Mitchell', 'Technical Support'),
(29, 'Ava Carter', 'Frontend Developer'),
(30, 'Benjamin Scott', 'Backend Developer'),
(31, 'Chloe Ward', 'Graphic Designer'),
(32, 'Daniel Lopez', 'Systems Engineer'),
(33, 'Emma Young', 'Mobile App Developer'),
(34, 'Finn Turner', 'IT Manager'),
(35, 'Giselle Parker', 'Software Engineer'),
(36, 'Hector Martin', 'Customer Support'),
(37, 'Isabel Wright', 'Sales Representative'),
(38, 'Jake Davis', 'Marketing Coordinator'),
(39, 'Kylie Adams', 'Financial Analyst'),
(40, 'Liam Hill', 'HR Specialist'),
(41, 'Mila Rogers', 'Legal Counsel'),
(42, 'Noah Coleman', 'Business Development'),
(43, 'Olivia Turner', 'Logistics Manager'),
(44, 'Peyton Foster', 'Event Planner'),
(45, 'Quentin Reed', 'Social Media Manager'),
(46, 'Riley Bennett', 'Data Analyst'),
(47, 'Sofia Phillips', 'Customer Success'),
(48, 'Tyler Nelson', 'E-commerce Specialist'),
(49, 'Uma Foster', 'Content Writer'),
(50, 'Victor Hayes', 'Public Relations'),
(51, 'Willa Wright', 'Sales Manager'),
(52, 'Xander Turner', 'Market Researcher'),
(53, 'Yasmine Mitchell', 'Training Coordinator'),
(54, 'Zachary Scott', 'Business Consultant'),
(55, 'Abigail Reed', 'Product Manager'),
(56, 'Blake Adams', 'Legal Advisor'),
(57, 'Cassandra Wilson', 'Research Scientist'),
(58, 'Dylan Wright', 'IT Specialist'),
(59, 'Ella Baker', 'Customer Experience'),
(60, 'Felix Turner', 'Operations Manager');
